### ISSUE TITLE
line break in GBrowse link for Cicer arietinum

### ISSUE THREAD

**Issue by amcooksey** [legumeinfo/legumeinfo.org#13]
https://legumeinfo.org/organism/Cicer/arietinum 
There is a line break in a link on the ‘Cicer arietinum’ page that makes it easy to overlook GBrowse as an option for desi

**Comment by adf-ncgr** [comment]
should be easy to fix. arbitrarily chose @sdash-github

**Comment by sdash-github** [comment]
Problem doesn't exist anymore at https://legumeinfo.org/organism/Cicer/arietinum in production nor in stage.
**Somebody must have taken care of it before.
In case, I am not able to see the problem, please help me understand where is the line-break. Else close as resolved.

**Comment by adf-ncgr** [comment]
it might be non-obvious if your browser happens to be the right width for it to be wrapped to the next line, but look for the text:
version is available here: Parween, S et al. 2015. GBrowse genome browser, cicar.ICC4958.v2.0

a line break should occur before the GBrowse

**Comment by sdash-github** [comment]
See it now. Thanks.

**Comment by sdash-github** [comment]
Fixed both in prod. and stage.
