### ISSUE TITLE
BLAST input doesn't allow trailing CR

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/legumeinfo.org#6]
I'd like the BLAST input form to be insensitive to a trailing CR in the sequence; for example, apply trim() to the string before validation. This matters because I'm getting a trailing CR from my mine sequence extractor that creates the form to post to LIS BLAST. Example attached with validation message.

![screenshot_2018-07-11 nucleotide to nucleotide blast blastn lis - legume information system](https://user-images.githubusercontent.com/5657219/42600553-ffa7fd8a-851f-11e8-88f1-5a6d715e92ce.png)

**Comment by ekcannon** [comment]
RegEx fixed in validate_fasta_sequence() - api/blast_ui.api.inc.

Also fixes https://github.com/LegumeFederation/tripal_blast/issues/6
