### ISSUE TITLE
highlight search instructions on 'map search' page

### ISSUE THREAD

**Issue by amcooksey** [legumeinfo/legumeinfo.org#7]
The instructions are clear but I suspect no one reads them. Could we make this statement more obvious?: "Leave both fields empty and click search to see a list of all maps. "

**Comment by amcooksey** [comment]
This issue also applies to PeanutBase

**Comment by ekcannon** [comment]
Not too many options for making this more visible. Did move it to the end of the text so that it isn't embedded.

Changes can be seen on the peanutbase and lis staging servers. PeanutBase includes additional verbiage about map names.
